[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "061d1955aeee51760087572ac607e0b6f22aaa04"
os = "macos"

    [[SSGraphBLAS.download]]
    sha256 = "25fa259c1253ef4b83080e3df002e37042027e528bf1f0f20a9e4dca5af8e4de"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.aarch64-apple-darwin.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "81561794a6879a40e9a88a96ba34e968bddfa59c"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "73d4f0fb2f19bfdc4fb0dcfbf5a1be5b09a3500d99239023429300d3091549e6"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.aarch64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "a16e2a467f2f3b2e0f80c56d764dad7759f62b88"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "831fef93f6dc7e33b9722293a2a196dddff9c381fcf785efee14b00737925cba"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.aarch64-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "fda5caee3a04bda7487e011137d7a0678c70e477"
os = "freebsd"

    [[SSGraphBLAS.download]]
    sha256 = "1c1ee9e0b7216ce79ec97c3d60bbee6aad1d957d3a588f8d27025c8e9ac94e74"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.aarch64-unknown-freebsd.tar.gz"
[[SSGraphBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "44aedab224859276f5cfab7b75a3d4d735b280da"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "b7cb224325975ac907decff6be19fd1a599e8a342160c2275b8bad1d4ad329a2"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.armv6l-linux-gnueabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e405e1bc2b5b294fdd042c83201dc3a246c30b11"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "4e124019d050b108a99bb43285aedc2c93d948bd821c9537029a08332212273e"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.armv6l-linux-musleabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a3dc13d3bac179bb9c9c086693787d41ebb647fd"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "08ae785cf83d3140b2c4db033df0894107984676bd8c7e0743e5598f6ae3c301"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.armv7l-linux-gnueabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cff128a3cb40e64ed0df5eea56219c4c3da203a4"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "85ca2b7147da2b750e15205fc87413672ee32ab5d6e95e2bd7eca9ce38e65a07"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.armv7l-linux-musleabihf.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "1063b98e314537cd91a84c74a50fb17888dd3d23"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "2aa31f26592b8b6d5c01a9b9d5803aa4f5fc2050daa46de292c6f4058b97a623"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.i686-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "bc014df254f4505c385cc0ac931d0d8025578c6c"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "dbaec656cf0b91270489cf1bbd9685c3c85a27459c8deb6f0c03d7fd388150b2"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.i686-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "3a9f1c18d32445224d05bc6ee5ac60660ebfb9e1"
os = "windows"

    [[SSGraphBLAS.download]]
    sha256 = "498431938e405a17cc8511f143a6357e21359122cf100c583645d562cbcffe3e"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.i686-w64-mingw32.tar.gz"
[[SSGraphBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "28db22eae7b94bd42194fc511c2e75b5f4bf82eb"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "cd9345767ab06ff19adebff4860798e29e8bc1e8303e7d9b656ce0d21f18b374"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.powerpc64le-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "riscv64"
git-tree-sha1 = "b561e4f4355deb503180014b12be9c46803173fb"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "63349f82736bece1ec316e54deb28ecb84744db8903aa9294e07deb3aaede088"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.riscv64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "94d3ddce24c3e297883de7fe451dd677bb8ef2ee"
os = "macos"

    [[SSGraphBLAS.download]]
    sha256 = "6adbe97859440e125519b4f2519c64153598fecd4bb7955ade515728c9575e9b"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.x86_64-apple-darwin.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "6cfe0154e96a388661c9f6604bb7861386646d08"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "d7ded8c9cc0142b8f506a16d29a3a5db6a7fd9ba20cebc85ecb4cbc3d5b8fcfb"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.x86_64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "ac154c221f2b2b8e4d07d468ef767a51161edd92"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "b255af2d892bfc5ade15482afe6d0f3ad4aa1724bc1cfb114369e84070fd7811"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.x86_64-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "a8be2dd8f2abb650ebafb18c6cfa6db34b07ea31"
os = "freebsd"

    [[SSGraphBLAS.download]]
    sha256 = "5f5592c101944e257a779480e1d01193bbe68522d954e25c63addf65e4c6f96b"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.x86_64-unknown-freebsd.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "5d5c060a826a88c0231791fa16df7fe6d04ca2dd"
os = "windows"

    [[SSGraphBLAS.download]]
    sha256 = "92cb228ab34b252faa08b09ff75a0c37a5610abf67a84df27b0467a52c438785"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.3.1+0/SSGraphBLAS.v10.3.1.x86_64-w64-mingw32.tar.gz"
