[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "d2252e42fe22190e4b449fd20bbb397036facdad"
os = "macos"

    [[SSGraphBLAS.download]]
    sha256 = "023758c2ad50ac253cc8dff35cdd4169d8c00497060a2f13a7ab416301e97dc3"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.aarch64-apple-darwin.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "5bf5501706749bb018892aa591c6193635db76d9"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "3bff3e712f61df0cff508722bb0df428bd0dac5fac3861d3495b450e6a2c4349"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.aarch64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "f01b7d3b5acf6e76c9b0d5f85379743434b51c1e"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "1e7a6381b1d8632ccaa82e9dec86be3680180d383fba9ae9e14ed9e2ba9fe263"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.aarch64-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "b5d1a55055a90777e20e6dcce6062bf7f634dd00"
os = "freebsd"

    [[SSGraphBLAS.download]]
    sha256 = "c0d34de1eecffa62dc368674d759767fa7e72c0bb9ab33468530315b99e96e9d"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.aarch64-unknown-freebsd.tar.gz"
[[SSGraphBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd347f196a9dc1ef45fce937e7e9632b73ce2341"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "133605e066803cc2267fec804b1c7bd1b3b88534f53cd81d323cb32fd89b4bc8"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.armv6l-linux-gnueabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5bb84f8c981dd62f9bf4cacea8d41d567e048256"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "a77b7714c05b59704862c6c816ba8b2621e5bea62f757520d0f5e96957101826"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.armv6l-linux-musleabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "303d85888981a727f54fedda36cad0c2df46aa1a"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "0824c41888d30789ccb8b0efd8e23f1bc4d7c7b5361510bbdb3a53ce439261d8"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.armv7l-linux-gnueabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "843c1ac40e51610e65df199a1e74f5faa97f504b"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "53bd8fce60ea5fd4396edfddd4338fe43c609b4b4cc5ce7dc6ab84627e1b698e"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.armv7l-linux-musleabihf.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "2e3678716a9d19db10eb86ed884a0889af396665"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "7f54666810a66d068302ccc1c4b61239dccb49ca384db3fab182baf435ab377f"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.i686-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "1c3ab0c44b69ae46208764b00ee3537b074dd492"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "1e6c7756597d37103b32c047c952416177a67832613a5d93d7ced0fdd594af54"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.i686-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "93d8864b5aa67fbe98b3ed7f87e72ef29b7db597"
os = "windows"

    [[SSGraphBLAS.download]]
    sha256 = "5b396f2161492cb8f4c39e2b9f565c6fb78f06af7e8dfdac6a0b3d63f4b12e16"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.i686-w64-mingw32.tar.gz"
[[SSGraphBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "5b5b3f0a497208df9fe25a3abce2e3e3bbbcf82d"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "5ab97438595d5da5c789ae16d5dc2bdfe3e815f42a4e8aa8ce1bf69faf41bfe8"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.powerpc64le-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "riscv64"
git-tree-sha1 = "cf3fca00684126cc475096bb0a3832d1215335c4"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "7ce16cd640989b11bb09932c012b65723528e8c8947c5650a6fa97d51cfd7410"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.riscv64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "6dd7f500a233faebc7ce4ac913db0b005e56ce77"
os = "macos"

    [[SSGraphBLAS.download]]
    sha256 = "eec7504f0ddee26121392aeae523c88664c4f2b2bdbef7c8c01c6cf99f83816c"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.x86_64-apple-darwin.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "6150ea6f95c4e7270d8d2dbd5e076ee474f86f8d"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "4ba949e1217bcb8134fe33b9424743d368157a5f51fe7f683d367639552e414d"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.x86_64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "0fd6426fd15ce324a52a5b8c4d453fc26b757fe3"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "db9d78619fcb187bce653363e7895192637733fabda8085f0ca5c19eb8ce1184"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.x86_64-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "de2614ead66c328189604956247d6deb235ce179"
os = "freebsd"

    [[SSGraphBLAS.download]]
    sha256 = "b66480da276bd6d02cf925926c8e0fc7416af18b9433a83e14e2323519c9bfb9"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.x86_64-unknown-freebsd.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "63279e3fde76e6aed4a9879fee274fce53b8a6ee"
os = "windows"

    [[SSGraphBLAS.download]]
    sha256 = "03a67513c74467a575691f85995029dd055781350e59d7a14a2d511775e74ce1"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.5.0+0/SSGraphBLAS.v10.5.0.x86_64-w64-mingw32.tar.gz"
