# Autogenerated wrapper script for SSGraphBLAS_jll for aarch64-apple-darwin
export libgraphblas

using libblastrampoline_jll
using LLVMOpenMP_jll
using SuiteSparse_jll
JLLWrappers.@generate_wrapper_header("SSGraphBLAS")
JLLWrappers.@declare_library_product(libgraphblas, "@rpath/libgraphblas.10.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, LLVMOpenMP_jll, SuiteSparse_jll)
    JLLWrappers.@init_library_product(
        libgraphblas,
        "lib/libgraphblas.10.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
